package io.github.defective4.sdr.owrxclient.model;

public enum Feature {
    ACARS, ADSB, AFEDRI, AIRSPY, AIRSPYHF, BLADERF, CORE, DAB, DIGITAL_VOICE_DIGIHAM, DIGITAL_VOICE_FREEDV, DIGITAL_VOICE_M17, DREAM_2_2,
    DRM, EAS, FCDPP, FIFI_SDR, HACKRF, HDRADIO, HFDL, HPSDR, HYDRASDR, ISM, JS8CALL, LIME_SDR,
    MALAHIT_RR, MIRICS, MP3, MQTT, MSK144, PACKET, PAGE, PERSEUSSDR,
    PLUTO_SDR, PNG, POCSAG, RADIOBERRY, RDS, RIGCONTROL, RTL_SDR, RTL_SDR_SOAPY, RTL_TCP, RUNDS, SDDC, SDDC_SOAPY, SDRPLAY, SELCALL, SKIMMER, SOAPY_REMOTE, UAT,
    UHD, VDL2, WSJT_X, WSJT_X_2_3, WSJT_X_2_4, WXSAT
}
